# Generated by Django 4.2 on 2024-04-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
