# Generated by Django 4.2 on 2024-04-18 02:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0002_article_like_user_articlelike"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="like_user",
        ),
        migrations.AddField(
            model_name="article",
            name="like_users",
            field=models.ManyToManyField(
                related_name="like_articles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
